trigger: none

pool: Agent VK

steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\Azure-Infra\envirornments\dev'
      backendServiceArm: 'ado_todo_svc'
      backendAzureRmStorageAccountName: 'vkstaorage'
      backendAzureRmContainerName: 'vkstate'
      backendAzureRmKey: 'terrafom.state'