trigger: none

pool: Agent VK

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/envirornments /dev'
    backendServiceArm: 'ado_todo_svc'
    backendAzureRmStorageAccountName: 'vkstaorage'
    backendAzureRmContainerName: 'vkstate'
    backendAzureRmKey: 'terraform.tfstate'


- task: tfsec@1
  inputs:
    version: 'v1.26.0'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/envirornments /dev'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/envirornments /dev'
    environmentServiceNameAzureRM: 'ado_todo_svc'


