trigger: none

pool: Agenet VK

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/envirornments /dev'
    backendServiceArm: 'ado_todo_svc'
    backendAzureRmStorageAccountName: 'vkstaorage'
    backendAzureRmContainerName: 'vkstate'
    backendAzureRmKey: 'terraform.tfstate'
